// Autogenerated from Pigeon (v22.6.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *BMLGetMessagesCodec(void);

@protocol BMLGCoreHost
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpBMLGCoreHost(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BMLGCoreHost> *_Nullable api);

extern void SetUpBMLGCoreHostWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BMLGCoreHost> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
